export const  CONVERTER_ACTION ='CONVERTER_ACTION';
export const SELECT_TO_CURRENY ='SELECT_TO_CURRENY';
export const SELECT_FROM_CURRENY ='SELECT_FROM_CURRENY';
export const SET_CURRENCIES ='SET_CURRENCIES';
export const CHANGE_AMOUNT = 'CHANGE_AMOUNT';
